# Generated by Django 2.1.2 on 2019-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='excel_text',
            field=models.CharField(default='your excel text here', max_length=100),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
