# Generated by Django 2.1.2 on 2019-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190109_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='excel_file',
            field=models.FileField(default='your file here', upload_to=''),
        ),
    ]
