# Generated by Django 2.1.2 on 2019-01-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dsaform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='home/exceldir')),
                ('excel_text', models.CharField(default='your excel text here', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
