# Generated by Django 2.1.2 on 2019-01-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190109_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dsauser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
