# Generated by Django 2.1.2 on 2019-01-15 17:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dsauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsauser',
            name='user_file',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
        migrations.AddField(
            model_name='dsauser',
            name='userfile_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dsaform',
            name='excel_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
    ]
