# Generated by Django 2.1.2 on 2019-01-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190115_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dsauserform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dsauser',
            name='user_name',
        ),
    ]
