# Generated by Django 2.1.2 on 2019-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190117_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.CharField(default='', max_length=100)),
                ('sem_name', models.CharField(default='', max_length=100)),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('dep_name', models.CharField(default='', max_length=100)),
                ('no_subs', models.CharField(default='', max_length=100)),
                ('period_total', models.CharField(default='', max_length=100)),
                ('sub_name', models.CharField(default='', max_length=100)),
                ('subnames_count', models.CharField(default='', max_length=100)),
                ('teacher_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dsauser',
            name='user_file',
            field=models.FileField(default='', upload_to='uploaded_docx_files/'),
        ),
    ]
